spring.application.name=app
server.port=8080
debug=true
spring.data.mongodb.database=Yoli
spring.data.mongodb.uri=mongodb+srv://testUser:testUser123@yoli.y9zus.mongodb.net/?retryWrites=true&w=majority&appName=Yoli